spring:
  application:
    name: fahabook
  datasource:
    url: jdbc:mysql://root:yMHPWJOeZQGjrWFuaSxiwiBqSKSncLwj@yamanote.proxy.rlwy.net:30917/railway
    username: root
    password: yMHPWJOeZQGjrWFuaSxiwiBqSKSncLwj
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 564809681010-j9tb6t9o5p64hrf9f9s7gvrfq51vnplo.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  jpa:
    properties:
      hibernate:
        globally-quoted-identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mobileapp084@gmail.com
    password: "omyh rtaj cvdi icos"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:/external/path/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  graphql:
    path: /graphql
    graphiql:
      enabled: true

openapi:
  service:
    api-docs: api-service
    title: API FahaBook
    version: 1.0.0
server:
  forward-headers-strategy: framework
cloudinary:
  cloud-name: dmdjbuvig
  api-key: 652981452525434
  api-secret: pgIYakDqMVAYHy9bo-vdyFl3k1o

vnpay:
  tmn-code: C0LUS1XF
  hash-secret: MRSUPJYDQQV713GJPX8IVD1XAJIEVVJI
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/payments/return
  version: 2.1.0
  command: pay
  currency-code: VND
  locale: vn
  bank-code: NCB
jwt:
  issuer: ngoctaiphan
  audience: ngoctaiphan
  expiration-minutes: 10080
  keys:
    private-key: classpath:keys/private_key.pem
    public-key: classpath:keys/public_key.pem
