spring:
  application:
    name: MobileAPI
  datasource:
    url: jdbc:mysql://localhost:3306/mobile
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: mobileapp084@gmail.com
    password: "omyh rtaj cvdi icos"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:/external/path/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  graphql:
    path: /graphql
    graphiql:
      enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0

cloudinary:
  cloud-name: drvydie5q
  api-key: 241959425679189
  api-secret: efKXKXZgID6nX_5tPItvYZn35rY

  admin:
    username: admin
    password: admin
